### ISSUE TITLE
请问有办法保存到固定的同一篇笔记上么？而不是一条记录新增一篇笔记

### ISSUE THREAD

**Issue by tyf2018** [xiaotianhu/obsidian-messager#2]
请问有办法保存到固定的同一篇笔记上么？而不是一条记录新增一篇笔记
![image](https://github.com/user-attachments/assets/0abdef50-04d9-492e-8ed8-e74658e4a145)

**Comment by xiaotianhu** [comment]
收到，考虑下哈。

**Comment by xiaotianhu** [comment]
加上了，可以试试哈。
